version: '3.8'

services:
  web:
    image: myapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - celery
      - postgres
      - redis
      - alembic
    env_file:
      - .env

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
    container_name: celery
    command: ["celery", "-A", "src.celery:celery_app", "worker", "-l", "INFO"]
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
    env_file:
      - .env

  alembic:
    build:
      context: .
    container_name: alembic
    depends_on:
      - postgres
    env_file:
      - .env
    command: ["alembic", "upgrade", "head"]

volumes:
  postgres_data:
