[tool.isort]
profile = "black"
line_length = 88
skip = "migrations, new_venv"
sections = ["STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
force_single_line = false
multi_line_output = 3
import_heading_localfolder = "Local Imports"
