"""empty message

Revision ID: 22e94efbf4c4
Revises: bcefc718aaf0
Create Date: 2025-01-09 11:12:27.443928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22e94efbf4c4'
down_revision: Union[str, None] = 'bcefc718aaf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('certificate_info', sa.String(), nullable=True))
    op.alter_column('students', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'surname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'surname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('categories', 'certificate_info')
    # ### end Alembic commands ###
