"""empty message

Revision ID: 31a5acad44ea
Revises: 22e94efbf4c4
Create Date: 2025-01-13 16:59:13.285175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a5acad44ea'
down_revision: Union[str, None] = '22e94efbf4c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('about_main_text', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('program_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'program_text')
    op.drop_column('courses', 'about_main_text')
    # ### end Alembic commands ###
