"""Create filed spent_minutes for ExamAttempts model

Revision ID: 3df8411775e1
Revises: 31a5acad44ea
Create Date: 2025-01-29 12:37:25.030023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3df8411775e1'
down_revision: Union[str, None] = '31a5acad44ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_exam_attempts', sa.Column('spent_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_exam_attempts', 'spent_minutes')
    # ### end Alembic commands ###
