"""added table notifications

Revision ID: 7b199785464a
Revises: 02ae65bb7e47
Create Date: 2024-04-12 15:43:53.789283

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7b199785464a'
down_revision: Union[str, None] = '02ae65bb7e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('change_course', 'added_course', name='notificationtype'), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_notifications_id'), 'student_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_student_notifications_student_id'), 'student_notifications', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_notifications_student_id'), table_name='student_notifications')
    op.drop_index(op.f('ix_student_notifications_id'), table_name='student_notifications')
    op.drop_table('student_notifications')
    # ### end Alembic commands ###
