"""add table for templates

Revision ID: d5fbb2256a1a
Revises: d01612eaeff9
Create Date: 2024-08-21 16:47:24.590850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5fbb2256a1a'
down_revision: Union[str, None] = 'd01612eaeff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('lecture', 'practical', name='lessontemplatetype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_templates_id'), 'lesson_templates', ['id'], unique=False)
    op.create_table('lecture_template_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column(
        'a_type',
        sa.Enum(
            'text',
            'present',
            'audio',
            'picture',
            'video',
            'file',
            'link',
            name='lectureattributetype',
        ).with_variant(
                postgresql.ENUM(
                    'text',
                    'present',
                    'audio',
                    'picture',
                    'video',
                    'file',
                    'link',
                    name='lectureattributetype',
                    create_type=False,
                ),  "postgresql",
        ),
        nullable=False),
    sa.Column('a_title', sa.String(), nullable=False),
    sa.Column('a_number', sa.Integer(), nullable=False),
    sa.Column('a_text', sa.String(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['lesson_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lecture_template_attributes_id'), 'lecture_template_attributes', ['id'], unique=False)
    op.create_table('practical_template_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('q_text', sa.String(), nullable=False),
    sa.Column('q_number', sa.Integer(), nullable=False),
    sa.Column('q_score', sa.Integer(), nullable=False),
    sa.Column(
        'q_type',
        sa.Enum(
            'test',
            'boolean',
            'answer_with_photo',
            'question_with_photo',
            'matching',
            'multiple_choice',
            name='questiontypeoption',
        ).with_variant(
            postgresql.ENUM(
                'test',
                'boolean',
                'answer_with_photo',
                'question_with_photo',
                'matching',
                'multiple_choice',
                name='questiontypeoption',
                create_type=False,
            ),  "postgresql",
        ),
        nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['lesson_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practical_template_questions_id'), 'practical_template_questions', ['id'], unique=False)
    op.create_table('lecture_template_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_description', sa.String(), nullable=True),
    sa.Column('download_allowed', sa.Boolean(), nullable=True),
    sa.Column('lecture_template_attr_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lecture_template_attr_id'], ['lecture_template_attributes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lecture_template_files_id'), 'lecture_template_files', ['id'], unique=False)
    op.create_table('lecture_template_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('anchor', sa.String(), nullable=True),
    sa.Column('lecture_template_attr_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lecture_template_attr_id'], ['lecture_template_attributes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lecture_template_links_id'), 'lecture_template_links', ['id'], unique=False)
    op.create_table('practical_template_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('a_text', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['practical_template_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practical_template_answers_id'), 'practical_template_answers', ['id'], unique=False)
    op.create_table('practical_template_matching_right',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['practical_template_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practical_template_matching_right_id'), 'practical_template_matching_right', ['id'], unique=False)
    op.create_table('practical_template_matching_left',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['practical_template_questions.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['practical_template_matching_right.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practical_template_matching_left_id'), 'practical_template_matching_left', ['id'], unique=False)
    op.add_column('categories', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.add_column('categories', sa.Column('timestamp_add', sa.DateTime(), nullable=True))
    op.add_column('categories', sa.Column('timestamp_change', sa.DateTime(), nullable=True))
    op.add_column('user_notes', sa.Column('text', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_notes', 'text')
    op.drop_column('categories', 'timestamp_change')
    op.drop_column('categories', 'timestamp_add')
    op.drop_column('categories', 'is_published')
    op.drop_index(op.f('ix_practical_template_matching_left_id'), table_name='practical_template_matching_left')
    op.drop_table('practical_template_matching_left')
    op.drop_index(op.f('ix_practical_template_matching_right_id'), table_name='practical_template_matching_right')
    op.drop_table('practical_template_matching_right')
    op.drop_index(op.f('ix_practical_template_answers_id'), table_name='practical_template_answers')
    op.drop_table('practical_template_answers')
    op.drop_index(op.f('ix_lecture_template_links_id'), table_name='lecture_template_links')
    op.drop_table('lecture_template_links')
    op.drop_index(op.f('ix_lecture_template_files_id'), table_name='lecture_template_files')
    op.drop_table('lecture_template_files')
    op.drop_index(op.f('ix_practical_template_questions_id'), table_name='practical_template_questions')
    op.drop_table('practical_template_questions')
    op.drop_index(op.f('ix_lecture_template_attributes_id'), table_name='lecture_template_attributes')
    op.drop_table('lecture_template_attributes')
    op.drop_index(op.f('ix_lesson_templates_id'), table_name='lesson_templates')
    op.drop_table('lesson_templates')
    # ### end Alembic commands ###
