"""Add new table for Stripe data

Revision ID: ecd0b86fc219
Revises: 4639c278c22b
Create Date: 2024-10-07 11:40:03.239750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecd0b86fc219'
down_revision: Union[str, None] = '4639c278c22b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('stripe_product_id', sa.Integer(), nullable=False),
    sa.Column('stripe_price_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_courses_id'), 'stripe_courses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stripe_courses_id'), table_name='stripe_courses')
    op.drop_table('stripe_courses')
    # ### end Alembic commands ###
